services:
  postgres:
    image: postgres:16-alpine
    container_name: urlytix_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: urlytix
      POSTGRES_PASSWORD: urlytix_password
      POSTGRES_DB: urlytix_db
    ports:
      - "5432:5432"
    volumes:
      - urlytix_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: urlytix_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - urlytix_redis_data:/data

volumes:
  urlytix_postgres_data:
  urlytix_redis_data: